### ISSUE TITLE
Comenzar documentacion

### ISSUE THREAD

**Issue by vrt0004** [vrt0004/Trabajo#4]

**Comment by alvarag** [comment]
[MemoriaVictorRev.pdf](https://github.com/vrt0004/Trabajo/files/300226/MemoriaVictorRev.pdf)
Adjunto comentarios sobre la versión de la documentación que me descargué el martes pasado.

**Comment by alvarag** [comment]
Adjunto la memoria con comentarios.
[MemoriaRev.pdf](https://github.com/vrt0004/Trabajo/files/345947/MemoriaRev.pdf)

**Comment by alvarag** [comment]
Adjunto versión con comentarios de los anexos. Hay bastantes cosas que pulir, se nota que no han sido tan trabajados como la memoria y echo en falta algunos aspectos que te he comentado.
[anexosRev.pdf](https://github.com/vrt0004/Trabajo/files/346048/anexosRev.pdf)

**Comment by alvarag** [comment]
Desde mi punto de vista el anexo D queda muy pobre, no es útil para un posible alumno que quiera ampliar este proyecto.
