### ISSUE TITLE
Generar plantilla LaTeX

### ISSUE THREAD

**Issue by vrt0004** [vrt0004/Trabajo#9]

**Comment by alvarag** [comment]
Adjunto los documentos revisados, tienen buena forma pero hay que pulir bastantes detalles que te he indicado. Si alguna cosa no ha quedado clara, la hablamos el jueves.
[Memoria_revisada.pdf](https://github.com/vrt0004/Trabajo/files/313760/Memoria_revisada.pdf)
[anexos_revisada.pdf](https://github.com/vrt0004/Trabajo/files/313761/anexos_revisada.pdf)
